# Generated by Django 5.2.6 on 2025-10-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        ('productos', '0002_alter_producto_foto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado_incidente', models.CharField(choices=[('pendiente', 'Pendiente'), ('no_resuelto', 'No Resuelto'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquileres.alquiler')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
