# Generated by Django 5.2.6 on 2025-10-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'ordering': ['-fecha_incidente'], 'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidentes'},
        ),
    ]
